export const stocks = [
  {
    id: 1,
    logId: "log1",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 2,
    logId: "log2",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 3,
    logId: "log3",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 4,
    logId: "log4",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 5,
    logId: "log5",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 6,
    logId: "log6",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 7,
    logId: "log7",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
  {
    id: 8,
    logId: "log8",
    beefMayo: 50,
    ragout: 50,
    truffle: 50,
    kani: 50,
    saltedEgg: 50,
    beefMentai: 50,
    kornet: 50,
    bolognese: 50,
  },
];
